from setuptools import setup, find_packages

setup(
    name="housing-crisis-prediction-ensemble",
    version="1.0.0",
    description="Multi-Modal Stacked Ensemble Framework for Housing Crisis Prediction",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "xgboost>=2.0.0",
        "catboost>=1.2.0",
        "torch-geometric>=2.5.0",
        "transformers>=4.35.0",
        "fredapi>=0.5.0",
        "requests>=2.31.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.18.0",
        "pyyaml>=6.0",
        "tqdm>=4.66.0",
        "scipy>=1.10.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "jupyter>=1.0.0",
        ],
        "autogluon": [
            "autogluon.tabular>=1.1.0",
            "autogluon.timeseries>=1.1.0",
        ],
        "foundation": [
            "git+https://github.com/google-research/timesfm.git",
            "git+https://github.com/amazon-science/chronos-forecasting.git",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
